services:
  trading-harry:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shares_future
    environment:
      TZ: Europe/Berlin
    env_file:
      - .env
    volumes:
      - ./data:/app/data
